version: 2.1
jobs:
  sync:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run:
          name: install notion plugin
          command: pip install git-notion
      - run:
          name: sync documents with notion
          command: NOTION_IGNORE_REGEX="how to contribute.md|pre engineering\ principles.md" git-notion
workflows:
  version: 2
  sync:
    jobs:
      - sync:
          filters:
            branches:
              only: master